name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Checkout-source code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'temurin'

    # gradlew 권한 설정
    - name: Set gradlew permissions
      run: |
        chmod +x ./gradlew

    # gradle 빌드
    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Set SSH key permissions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}


    - name: Add known_hosts
      run: |
        ssh-keyscan -t ed25519 13.125.86.33 >> ~/.ssh/known_hosts
    
    #- name: 기존프로세스 종료
    #  run: |
    #    kill -9 $(ps -ef | grep devops | grep -v grep | head -n 1 | awk '{print $2}') || true
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: chaijewon/myapp:latest.

    - name: Login docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
        
      # docker hub 퍼블리시
    - name: Publish to docker hub
      run: docker push chaijewon/myapp:latest
      
    - name: Deploy to Server with rsync
      run: | 
         rsync -avz -e "ssh -o StrictHostKeyChecking=no" myapp.tar ubuntu@13.125.86.33:~/app


    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@13.125.86.33 << 'EOF'
          docker stop myapp || true
          docker rm myapp || true
          docker pull chaijewon/myapp
          docker run -d -p 8080:8080 --name springboot-myapp chaijewon/myapp
        EOF
